# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0ea3029e5ef591ae9fbfefdb78f23fee974280c9b1b34d0f8c4fd9a3d9f270c6779aba1bf0a3681b51c71d823850831cf0bccaae4346f778dc839c868d98c771

test:
  secret_key_base: 2d2f897b7981bef854854a786eb543d3abbef7a96ed12db31f2c2cfe544bb07f41c45e9959bf362e24175b44bc6bc4dd082832be22ac028653e401a78e113af3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
